server:
  applicationConnectors:
    - type: http
      port: 8080
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 8081
  rootPath: /api/*

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: app

  # the password
  password: app

  # the JDBC URL
  url: jdbc:mysql://ipwrc_db:3306/ipwrc-webshop

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level: INFO
  loggers:
    nl.mazeyar.ipwrc-webshop: DEBUG
